apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default

  source:
    repoURL: https://github.com/Dans9881/platform-k8s
    targetRevision: main
    path: k8s/infra/cert-manager

  destination:
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      prune: true
      selfHeal: true