resources:
  - cert-manager.crds.yaml

patches:
  - target:
      kind: CustomResourceDefinition
    patch: |
      - op: add
        path: /metadata/annotations
        value:
          argocd.argoproj.io/sync-wave: "0"