apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-ml
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Dans9881/platform-k8s
    targetRevision: main
    path: k8s/apps/flask-ml

  destination:
    server: https://kubernetes.default.svc
    namespace: flask-ml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true