apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-ml-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: tes.kuyen.online
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-ml
            port:
              number: 80