resources:
  - infra/traefik/application.yaml
  - infra/cert-manager/application.yaml
  - infra/cert-manager/clusterissuer.yaml
  - infra/monitoring/monitoring-stack.yaml
  - infra/monitoring/monitoring-ingress.yaml
  - infra/monitoring/manifests
  - apps/flask-ml/application.yaml