apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-all
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Dans9881/platform-k8s
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: argocd-cmd-params-cm
      namespace: argocd
      jsonPointers:
        - /metadata/labels