apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"

spec:
  project: default

  source:
    repoURL: https://github.com/actions/actions-runner-controller
    targetRevision: master
    path: charts/actions-runner-controller

    helm:
      values: |
        installCRDs: false
        authSecret:
          create: false
          name: controller-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: actions-runner-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true