service:
  type: NodePort

  spec:
    ports:
      - name: web
        port: 80
        targetPort: web
        nodePort: 30080

      - name: websecure
        port: 443
        targetPort: websecure
        nodePort: 30443

ports:
  web:
    expose: true

  websecure:
    expose: true