apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: traefik
spec:
  chart: traefik
  repo: https://traefik.github.io/charts
  targetNamespace: traefik

  valuesContent: |-
    service:
      type: NodePort

    ports:
      web:
        port: 80
        nodePort: 30080
      websecure:
        port: 443
        nodePort: 30443

    additionalArguments:
      - "--api.dashboard=true"
      - "--api.insecure=true"