resources:
  - root-app.yaml
  - apps/flask-ml.yaml
  - infra/traefik.yaml
  - infra/cert-manager.yaml
  - infra/monitoring-crds.yaml
  - infra/monitoring-extra.yaml
  - infra/monitoring.yaml
  - infra/ci-controller.yaml
  - infra/ci-runner.yaml
  - infra/ci-controller-crds.yaml