apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`grafana.local`)
      kind: Rule
      services:
        - name: monitoring-grafana
          port: 80