apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: actions-runner
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsiYXV0aCI6IlpHRnVjems0T0RFNlpHTnJjbDl3WVhSZmR6RjJTRVF0TTJ3emFtSm9abUpCUTBGelQwZHJjVVpMYTBkViJ9fX0=