apiVersion: v1
kind: Secret
metadata:
  name: docker-config
  namespace: actions-runner
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkYW5zOTg4MSIsInBhc3N3b3JkIjoiZGNrcl9wYXRfdzF2SEQtM2wzamJoZmJBQ0FzT0drcUZLa0dVIiwiYXV0aCI6IkJBU0U2NCJ9fX0=