apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: runner-restrict
  namespace: actions-runner

spec:
  podSelector:
    matchLabels:
      app: github-runner

  policyTypes:
    - Ingress
    - Egress

  ingress: []  # deny all ingress

  egress:
    # ALLOW DNS
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53

    # ALLOW KUBE API (INI YANG PENTING)
    - to:
        - ipBlock:
            cidr: 10.96.0.1/32
      ports:
        - protocol: TCP
          port: 443

    # ALLOW INTERNET (buat pull image / github)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 80