apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: runner-restrict
  namespace: actions-runner

spec:
  endpointSelector:
    matchLabels:
      app: github-runner

  ingress: []

  egress:
    - toEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: kube-system
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP

    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP