apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: github-runner
  namespace: actions-runner
spec:
  replicas: 1

  serviceName: github-runner

  selector:
    matchLabels:
      app: github-runner

  template:
    metadata:
      labels:
        app: github-runner

    spec:
      repository: Dans9881/flask-ml-app

      containers:
      - name: runner
        image: summerwind/actions-runner:latest

        env:
        - name: BUILDKIT_HOST
          value: tcp://localhost:1234

        volumeMounts:
        - name: docker-config
          mountPath: /home/runner/.docker
          readOnly: true

        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]

      - name: buildkit
        image: moby/buildkit:rootless

        args:
          - --addr
          - tcp://0.0.0.0:1234

        env:
        - name: BUILDKITD_FLAGS
          value: --oci-worker-no-process-sandbox

        volumeMounts:
        - name: docker-config
          mountPath: /home/user/.docker
          readOnly: true

        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]

      volumes:
      - name: docker-config
        secret:
          secretName: docker-config