apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: github-runner
  namespace: actions-runner

spec:
  replicas: 1

  repository: Dans9881/flask-ml-app

  selector:
    matchLabels:
      app: github-runner

  serviceName: github-runner

  template:
    metadata:
      labels:
        app: github-runner

    spec:
      serviceAccountName: runner-sa

      securityContext:
        fsGroup: 1000

      containers:
      - name: runner
        image: summerwind/actions-runner:latest

        env:
        - name: RUNNER_REPO
          value: Dans9881/flask-ml-app

        - name: RUNNER_EPHEMERAL
          value: "true"

        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]