apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: github-runner
  namespace: actions-runner

spec:
  replicas: 1
  repository: Dans9881/flask-ml-app
  serviceName: github-runner
  githubConfigSecret: github-token
  dockerEnabled: false

  selector:
    matchLabels:
      app: github-runner

  template:
    metadata:
      labels:
        app: github-runner

    spec:
      serviceAccountName: runner-sa
      automountServiceAccountToken: true

      securityContext:
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault

      volumes:
        - name: work
          emptyDir: {}
        - name: tmp
          emptyDir: {}

      containers:
        - name: runner
          image: dans9881/runner:latest

          env:
            - name: RUNNER_EPHEMERAL
              value: "true"

          volumeMounts:
            - name: work
              mountPath: /runner/_work
            - name: tmp
              mountPath: /tmp

          securityContext:
            runAsUser: 1001
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault