---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: actions-runner
spec:
  encryptedData:
    token: AgBQ9nqlAyLrM5L+MrpxhQ2bVBxQ2klA4N/NHAMOBFihWNY/XcWXrvHilmAnRDyvaOVFfoiTGHePspN0TWbnWIpmJmb3tLR5zUe6BZcPfIHQXlZAWrN5bunAPnBdwiLxPsu9FF132e2ZPevKdyOJWjDDmse2w7K7wOCVFWw+LQVYdKvA4auddIZvTzNqkfLu3ahF38AX/6MyREUL9yo4UfeIXRKpJuhydOq2mciGC/B6o3Lkhppkdm6dV6SKzUp2olZRnDK+XohC/AIYClsLLvgZO2m1UeF7e6nZ4rW10JFIt6Ni7FvUksLpxy9ckI9tNneqGK0Vw8DpL6uuzgv3w4PKguYiU6DMdLD1o0UQAKVkBJjj/MIkwD4nMQ480JN8KX4y6rTxY3CRdRaY8XMDqofHd1MwLS+/T+KegFNWvS48wtKjrGGuNWcfQe8pkkniNUE8ZdxuTRPSw9UcGzQ13TwYIQpEDI4Ob4fh2hrb5pdeDxvXjAZrjqdjseycTyoh+Cg3mCIAkIyWPl+zY3hteNzVmp+gqEe0n9i8f5n7brwrvyr+PMzsFG5Iz3VIgTInxEEQGT5Uf615iwWq01exES6K0zBGLdmUaB7Mr2LWC7/vnB/x40sojWhe3T3SK8wEd2rKKEvA8pPtOlGL/Q4RvlGA4gY6uL/YH8ubeZcFdcI8d+C9jPthh2akDlJGURT9LF/F/SHi7kgl/fjGKtmljkd/bBZ9wXPj4pfyf0STsNDgYoT01vVpuSSx
  template:
    metadata:
      name: github-token
      namespace: actions-runner