apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flask-ml
  namespace: flask-ml

spec:
  entryPoints:
    - websecure

  routes:
    - match: Host(`tes.kuyen.online`)
      kind: Rule
      services:
        - name: flask-ml
          port: 80

  tls:
    certResolver: letsencrypt